
pipeline:
  agent:
    any
  stages:
    - stage: Build
      steps:
        - script:
            script: |
              def deploymentYamlContent = """
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: poojaimages
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: poojaimages
                template:
                  metadata:
                    labels:
                      app: poojaimages
                  spec:
                    containers:
                      - name: customer-services
                        image: \${NEXUS_DOCKER_REPO}/Poojaimages:1.0.1
                        ports:
                          - containerPort: 9097
              """
              writeFile file: 'k0s-deployment.yaml', text: deploymentYamlContent

    - stage: Post-Build
      post:
        success:
          - archiveArtifacts:
              artifacts: 'k0s-deployment.yaml'
              onlyIfSuccessful: true
          - archiveArtifacts:
              artifacts: 'service-deployment.yaml'
              allowEmptyArchive: true
